Update process_output_urls.yml

diff --git a/.github/workflows/process_output_urls.yml b/.github/workflows/process_output_urls.yml
--- a/.github/workflows/process_output_urls.yml
+++ b/.github/workflows/process_output_urls.yml
@@ -12,7 +12,7 @@ jobs:
 
     - name: Select and split URLs
       run: |
-        shuf -n 800 output_urls.txt > selected_urls.txt
+        shuf -n 1000 output_urls.txt > selected_urls.txt
         split -n l/20 -d selected_urls.txt url_part_
 
     - name: Upload URL parts
@@ -75,6 +75,7 @@ jobs:
       run: |
         cd archivebox_data
         while IFS= read -r url; do
+          echo "Processing: $url"
           api_response=$(curl -s -w "\n%{http_code}" "http://archive.org/wayback/available?url=$url")
           http_code=$(echo "$api_response" | tail -n1)
           api_content=$(echo "$api_response" | sed '$d')
@@ -82,14 +83,18 @@ jobs:
           if [ "$http_code" = "200" ]; then
             archived_snapshots=$(echo "$api_content" | jq -r '.archived_snapshots')
             if [ "$archived_snapshots" = "{}" ]; then
-              echo "Archiving: $url"
-              archivebox add "$url" > /dev/null 2>&1
+              echo "Not archived. Archiving: $url"
+              if ! archivebox add "$url" > /dev/null 2>&1; then
+                echo "Error archiving $url"
+              fi
             else
-              echo "Skipping: $url"
+              echo "Already archived. Skipping: $url"
             fi
           else
-            echo "API call failed. Archiving: $url"
-            archivebox add "$url" > /dev/null 2>&1
+            echo "API call failed or rate limited. Archiving to be safe: $url"
+            if ! archivebox add "$url" > /dev/null 2>&1; then
+              echo "Error archiving $url"
+            fi
           fi
         done < ../url_part_$(printf "%02d" ${{ matrix.part }})
 
